name: Ruby specs

on: [push]

jobs:
  test:
    name: Ruby specs
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        ruby: ['2.7', '3.0']

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Ruby specs
        run: bundle exec rspec
